### ISSUE TITLE
[Interview] Champion Series Chris Lloyd-Jones

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#133]
## Article Details
_Please enter the details here_

**Proposer**: (who is proposing this article idea, Name | Affiliation | GitHub Username)
**Abstract**: (50 word summary of the article)
**Why**: (Why is this article an important topic to discuss and how is it related to the work/mission/theory of change of the GSF)
**Audience**: (Which audience is most going to connect to the content in this article)
**Timeline**: (Should this article come out before or after an important date)

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
**Questions**

What inspired you to focus on the intersection of software engineering and environmental sustainability?
In the last 5 years, has there been any particular initiative or project that you felt was truly catalytic in advancing a green transition in software? 
What advice would you give to software engineers who are passionate about building green software?
Are you happy with how you have balanced your role as a "tech generalist" with your commitment to climate activism in the tech industry?
How do you see collaboration and partnerships shaping the future of green software and a more sustainable tech culture?
Where will you focus most of your energy in the next 2 years?

**Comment by NAMRATA-WOKE** [comment]
@ursvill Chris has shared his answers:

What inspired you to focus on the intersection of software engineering and environmental sustainability?
My career path led me from law to technology initially - and I had an interest in environmental law at university. After my career change, my mindset was still pretty fixed on what I could see in the world around me - plastics, e-waste, and the effects of pollution - I hadn't considered the carbon of our software all! I first started thinking about technologies's own environmental impact during the lockdowns of the COVID19 pandemic, seeing the temporary changes in air pollution, and the fall of carbon dioxide emissions. I'd been tinkering and thinking, and when I saw the launch of the Green Software Foundation in 2021, I immediately knew this was the type of organisation I'd been looking for - and I think Avanade joined within a month or two.
We need to find a new stability and status quo in our use of resources - and that plays into my own interest in societal changes.

In the last 5 years, has there been any particular initiative or project that you felt was truly catalytic in advancing a green transition in software?
Over the last five years, I think many initiatives have focused on a green transition in software - the shift towards open-source solutions and energy-efficient coding practices has been significant; but controversially, I think people started to focus on efficiency as a byproduct of memory safety in languages like Rust, thinking about load times in interpreted severless deployments of Python, or to support processing on resource constrained hardware, like IoT devices... tl;dr, we weren't looking for sustainability, we were looking for efficiency, and then people cottoned onto the benefits of sustainability in general.
Now, seeing the rise of sustainably powered cloud computing, from the hyperscalers to regional players, I think sustainability as a measurement is here to stay.

What advice would you give to software engineers who are passionate about building green software?
Think about what you're building your software with, and why, before you then consider efficiency. For example, if you will always deploy to the same operating system, then a native application might be more efficient than an electron or cross-platform app.
Consider how much you are importing and using, when using an open source package - does it come with its own tree of dependencies, features, and unused code paths?
Talk to your peers, join a meetup, stay updated on the best practices and technologies that promote sustainability; and never underestimate the difference a single person can make.

Are you happy with how you have balanced your role as a "tech generalist" with your commitment to climate activism in the tech industry? While there's always room for growth, I'm pleased with how I've aligned my passion for sustainability with my day-to-day role - mission-driven work is important to me and keeps me happy and contented!

How do you see collaboration and partnerships shaping the future of green software and a more sustainable tech culture?
Collaboration and partnerships are essential in driving sustainable practices in technology. Companies can share knowledge, resources, and innovation by working together, speeding up the transition to green software. This cooperative approach fosters a collective responsibility for our planet and helps us achieve greater sustainability in the tech industry.
Right now though, I don't think we have enough collaboration - I'm hoping the Green Software Foundation will become a hub for this, bringing together passionate people to solve problems, rather than re-inventing the wheel in different locations and groups. We're two years in - we've defined the measurements, we've created amazing tools, now we need to work with the tech industry to continue to evangelise what exists.

Where will you focus most of your energy in the next 2 years?
In the next two years, at least with the Green Software Foundation, I will focus more of my time in communities, early talent, and building bridges. To be more specific, I want to ensure the Green Software Foundation is out there in the community with meetup groups beyond large cities like London. I'd love us to work and collaborate with other open source foundations to drive the type of adoption of the Carbon Aware SDK and other tools, along the lines of Docker or Kubernetes. And finally, I want to work with university and apprenticeship partners to push the green software awareness earlier along the educational pathway.

Personally? Anything that lets me work with interesting people, build new things, and make an impact is what I look for!

**Comment by ursvill** [comment]
https://docs.google.com/document/d/173ZGQdwJsjx5Pjc8obc2jXDkpZydXcfd/

@NAMRATA-WOKE - draft ready in case you want to edit

**Comment by ursvill** [comment]
@Jenya-design - Hi Jenya, this is a new blog interview series focusing on accomplished personalities in the green software space. We will need an image or two.

**Comment by ursvill** [comment]
![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/0ae3be5d-a186-4dcc-9a72-e9d62e699293)



![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/b97d9097-a2bb-4c5f-bc8d-8059d957af99)

**Comment by Jenya-design** [comment]
Thank you @ursvill please let me know what's my deadline for this article

**Comment by ursvill** [comment]
@Jenya-design - sometime next week would be great

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE please check the update attached and [on Drive](https://drive.google.com/file/d/13YrAnqKZdqVOB_db74l92xa3rkSUH8RO/view?usp=drive_link)
I made it in the same style as the Champion Series with [Chris Adams](https://drive.google.com/file/d/1gvas2uKlicBJSPqydDajIG6VyXGjT-s3/view?usp=drive_link)

![Champion-Series-Chris-Lloyd-Jones-Green-Software-Foundation](https://github.com/Green-Software-Foundation/writers/assets/69306070/a4bf4015-5507-4493-9636-668a416f26e4)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - let me know if you want to do a review, otherwise we can publish this week

**Comment by NAMRATA-WOKE** [comment]
@ursvill yes let me do a quick review and confirm soon.

**Comment by NAMRATA-WOKE** [comment]
@ursvill I finished by editing etc. Take a look. Also ready for publishing. Let's publish the AI article first - Tuesday. This one on Thursday. 

Thanks!

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published

**Comment by ursvill** [comment]
@NAMRATA-WOKE - did you share this, can I close it?

**Comment by NAMRATA-WOKE** [comment]
@ursvill yup, shared it, can close!
